language: c
os: linux
services: docker
cache:
  directories:
  - $HOME/.cache/pip
install:
  - docker pull continuumio/miniconda3
  - docker run -i -t continuumio/miniconda3 -v ~/.cache/pip:/root/.cache/pip /bin/bash -c "pip install tox-conda"
script:
  - docker run -i -t continuumio/miniconda3 -v $(pwd):/project -v ~/.cache/pip:/root/.cache/pip /bin/bash -c "cd /project && tox -e py37"
