language: c
os: linux
services: docker
cache:
  directories:
  - $HOME/.cache/pip
install: docker pull njzjz/tox
script: docker run -i -t -v $(pwd):/project -v ~/.cache/pip:/root/.cache/pip --env-file <(env | grep 'TRAVIS\|CI') njzjz/tox /bin/bash -c "chown -R root /root/.cache && cd /project && tox -e py37"
