version: 2.1
jobs:
  tox:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: sudo pip install tox && tox
workflows:
  version: 2.1
  test:
    jobs:
      - tox
